apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-api
  template:
    metadata:
      labels:
        app: loan-api
    spec:
      containers:
      - name: loan-api
        image: mumerarif/kedro_pipelines:fraud_detection_api_v2 # <--- Use the new tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # This tells the API how to find MLflow inside the cluster
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: MODEL_NAME
          value: "loan_xgb_model"
        - name: MODEL_ALIAS
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: loan-api-service
spec:
  type: ClusterIP
  selector:
    app: loan-api
  ports:
  - port: 80
    targetPort: 8000