# 1. MLFLOW DEPLOYMENT (Using the universal Kedro image)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  strategy:
    type: Recreate # Ensures only one pod accesses the SQLite DB at a time
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow-server
          image: mumerarif/kedro_pipelines:latest
          command: ["mlflow"]
          args:
            - "server"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "5000"
            - "--backend-store-uri"
            - "sqlite:///mlflow-data/mlflow.db" # Database on PVC
            - "--default-artifact-root"
            - "mlflow-artifacts:/"         # <--- CHANGE THIS
            - "--artifacts-destination"
            - "/mlflow-data/artifacts"
            - "--serve-artifacts"
            - "--allowed-hosts"
            - "*"
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow-data          # This matches the volumes section
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc1
        # env:
        #   # This tells the underlying server to ignore the Host header check
        #   - name: MLFLOW_GUNICORN_OPTS
        #     value: "--forwarded-allow-ips='*' --proxy-allow-from='*'"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow-data
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc1
---
# 2. MLFLOW INTERNAL SERVICE
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: mlflow
  type: ClusterIP
---
# 3. LOAN API DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-api
  template:
    metadata:
      labels:
        app: loan-api
    spec:
      containers:
      - name: loan-api
        image: mumerarif/kedro_pipelines:latest # Standardized tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # READINESS PROBE: API won't get traffic until artifacts are synced
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: MODEL_NAME
          value: "loan_xgb_model"
        - name: MODEL_ALIAS
          value: "production"
---
# 4. LOAN API PUBLIC SERVICE
apiVersion: v1
kind: Service
metadata:
  name: loan-api-service
spec:
  type: LoadBalancer 
  selector:
    app: loan-api
  ports:
  - port: 80
    targetPort: 8000

# kubectl apply -f pvc.yaml
# kubectl apply -f deployment.yaml
# kubectl get pods
# kubectl get service loan-api-service
# kubectl describe pod loan-api-deployment-577f75c74b-6hdkp (for inspection of not running pod)
# kubectl get svc loan-api-service
# kubectl port-forward svc/loan-api-service 8080:80
# kubectl port-forward svc/mlflow-service 5000:5000
# kubectl delete deployment deployment_name
# kubectl delete service service_name
# kubectl delete pod pod_name
# kubectl logs -l app=loan-api -f  #to see all the logs
# kubectl rollout restart deployment dep_name